name: Checks

on: push

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Run eslint
        run: yarn lint
      - name: Run prettier
        run: yarn prettier
      - name: Run bundlewatch
        run: yarn bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_REPO_OWNER: SiTaggart
          CI_REPO_NAME: PortfolioSite
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          CI_BRANCH: ${{ github.ref }}
          CI_BRANCH_BASE: main
      - name: Run percy
        run: yarn cypress:ci
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
